### ISSUE TITLE
Баг с камерой

### ISSUE THREAD

**Issue by Ryize** [Ryize/Volma#4]
При старте игры в новой комнате, камера перестаёт нормально работать. Перемещения, невозможность ходить и т.д.

**Comment by MrFireDeN** [comment]
Думаю, что нужно уменьшить персонажа. У FPSContoller'а есть capsule collider. Надо уменьшить его размер для новой комнаты.

**Comment by Ryize** [comment]
Помогло создании е нового FPSController'а, у старого слетели важные параметры
